### ISSUE TITLE
Incompatible for macOS

### ISSUE THREAD

**Issue by 0xMYsteRy** [Godofcoffe/FisherMan#1]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mystery/Desktop/FisherMan/fisherman.py", line 275, in <module>
    main(fs.args)
  File "/Users/mystery/Desktop/FisherMan/fisherman.py", line 259, in main
    browser = Firefox(options=options)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 

Please fix for macOs.

**Comment by Godofcoffe** [comment]
sorry for the delay, this error was due to the lack of "geckodriver" installed on your machine. Use this link to download it: https://github.com/mozilla/geckodriver/releases/latest. You will have a .zip for your platform.
If in case there is another error or a suggestion, make another issue.
Thanks.

**Comment by Godofcoffe** [comment]
One more thing... to finish the installation, copy the executable to the `/usr/bin` directory

**Comment by 0xMYsteRy** [comment]
Thank you for your great reponse. It works!
