### ISSUE TITLE
Traceback (most recent call last):   

### ISSUE THREAD

**Issue by moamed018** [Godofcoffe/FisherMan#12]
Traceback (most recent call last):   
File "C:\Users\محمد\FisherMan\fisherman.py", line 92, in <module>     
browser = little_fish._boot()   
File "C:\Users\محمد\FisherMan\src\fisherman\FisherMan.py", line 765, in _boot     
_options.add_argument("--incognito") AttributeError: 'Options' object has no attribute 'add_argument'

I use windows and edge drive

**Comment by Godofcoffe** [comment]
Okay, I will work on it at the beginning of the week, I just ask for a little patience from you.
