### ISSUE TITLE
Time limit exceed

### ISSUE THREAD

**Issue by Plutogithub2022** [Godofcoffe/FisherMan#13]
[*] logging into the account: gmarquizn@gmail.com
[*] Coming in https://www.facebook.com/***
[-] time limit exceeded
[-] time limit exceeded
^CTraceback (most recent call last):
  File "fisherman.py", line 104, in <module>
    little_fish._scrape(browser, cli.username)
  File "/home/secureuser/FisherMan/src/fisherman/FisherMan.py", line 532, in _scrape
    output = wbw.until(ec.presence_of_element_located((By.CLASS_NAME, 'f7vcsfb0')))
  File "/home/secureuser/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 77, in until
    time.sleep(self._poll)
KeyboardInterrupt

**Comment by Plutogithub2022** [comment]
Hello Godofoffe,
     I'm using  the latest of Ubuntu OS on VM and connecting with VPN.
Appreciate for your support this issues,

Thanks,

**Comment by Godofcoffe** [comment]
You can just tell me or send me a screenshot.

**Comment by Plutogithub2022** [comment]
Hi Kevin,
      I try to used -b arg as your advise,the browser is opening to run the process and it seems the credential of facebook account is invalid.
![Capture2](https://user-images.githubusercontent.com/98005352/162331912-beef3b29-e7a3-474a-b3c0-470bd51d7912.JPG)
.

**Comment by Godofcoffe** [comment]
Ok, I'll see what I can do, but just out of curiosity what version of the program are you using?
