### ISSUE TITLE
Login not "clickable"? 

### ISSUE THREAD

**Issue by Grenzland** [Godofcoffe/FisherMan#4]
Traceback (most recent call last):
  File "/Users/chrisfrei/FisherMan/fisherman.py", line 610, in <module>
    raise error
  File "/Users/chrisfrei/FisherMan/fisherman.py", line 600, in <module>
    login(browser)
  File "/Users/chrisfrei/FisherMan/fisherman.py", line 518, in login
    ok.click()
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: Element <button id="u_0_d_Bp" class="_42ft _4jy0 _6lth _4jy6 _4jy1 selected _51sy" name="login" type="submit"> is not clickable at point (963,303) because another element <div class="_3ixn"> obscures it

**Comment by Godofcoffe** [comment]
It seems to be a new exception in the browser, it doesn't seem to be complicated, but it is very specific for you so I will kindly ask you for 2 things: tell me which version you are using, Windows or standard (linux) and also use the -b argument in the program to display the browser, when the error happens take a printout of it and send it to this issue.

**Comment by Grenzland** [comment]
I am using a Mac 
When using the -b argument it opens Firefox, then Facebook. Then it asks for the acceptance for cookies. 
As far as I remember this is not usual outside the EU. Maybe that's the problem?

https://abload.de/img/bildschirmfoto2021-09tyjsn.png

**Comment by Godofcoffe** [comment]
I see, I had this in mind before, the login button is not clickable because it has this window and events like the "click" type are disabled. I will take a look at the selenium documentation to add a parameter to disable these windows.

**Comment by Godofcoffe** [comment]
My fear is that it won't, and then I would have to manually "click" with the selenium, and that would be tricky.

**Comment by Grenzland** [comment]
One way to "fix" the problem is to use an American IP. 

Not the most elegant way but it works.

**Comment by Godofcoffe** [comment]
I understand... I will consider it

**Comment by Godofcoffe** [comment]
I will still add a few more things to the patch, and I am kind of on a trip, so the new update might come out on Monday or Tuesday.

**Comment by Godofcoffe** [comment]
Hello, I have searched and thought a lot and realized that this is a rather complex problem, I tried to add a preference, an exception to always accept cookies from "facebook.com", but there is no setting for this apparently.
I could use a proxy but that would be unstable because I have no way to test it and errors could occur on other machines with this configuration.

**Comment by Godofcoffe** [comment]
As your case is isolated, I hope you forgive me but you will need to use a vpn or whatever method you have to make the program work. I will not forget this and will continue to study how to solve it as it may happen more often in the future.

**Comment by LoulouChabChab** [comment]
I have the same issue, I tried to use VPN but still not working
